name: meu_gabarito
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  build_runner: ^2.4.7
  cloud_firestore: ^4.15.5
  email_validator: ^2.1.17
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_mobx: ^2.2.0+2
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  mobx: ^2.3.0+1
  mobx_codegen: ^2.6.0+1
  path: ^1.8.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - .env
    - assets/
    - assets/img/
  uses-material-design: true
